name: Go
on:
  push:
    branches: 
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go mod download

    - name: Build
      run: mkdir bin && go build -v -o bin ./cmd/...
    
    - name: Test
      run: go test -v  ./...

    - name: Serverless
      uses: serverless/github-action@v1.53.0
    
    - name: Setup AWS
      run: sls config credentials --provider aws --key ${{secrets.AWS_KEY}} --secret ${{secrets.AWS_SECRET}}
    
    - name: Setup Config
      run: |
        echo "BOT_TOKEN: ${{secrets.BOT_TOKEN}}" > config.dev.yml
      
    - name: Deploy
      run: sls deploy
